kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: wordpress-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  MYSQL_DATABASE: mydb 
  MYSQL_USER: demo
  MYSQL_PASSWORD: rootpassword123
